[package]
name = "solvus"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.14.0"
garaga = { git = "https://github.com/keep-starknet-strange/garaga", tag = "v1.0.1" }

[cairo]
sierra-replace-ids = false

[dev-dependencies]
snforge_std = "0.53.0"
assert_macros = "2.14.0"

[[target.starknet-contract]]
sierra = true
casm = true
casm-add-pythonic-hints = true
